### ISSUE TITLE
issue with libstableR

### ISSUE THREAD

**Issue by ghost** [shill1729/findistr#1]
Sean hope everything is good with you. I am writing to see if you can help with the libstableR dependecies:
-libstableR::stable_fit_mle
-libstableR::stable_cdf
It seems libstableR is discontinued and when I try to install it, it says: "fatal error: too many errors emitted, stopping now".
I do thank you in advance for your support and consideration. ?nico

**Comment by shill1729** [comment]
Hi @rnfermincota 

Indeed, it seems it was removed from CRAN on 2023-06-02 because issues were not fixed in time. You can try to download the original published package from the [JSS post](https://www.jstatsoft.org/article/view/v078i01) by the authors.

Meanwhile, I will work on replacing this dependency with the new version by the same authors: 'libstable4u' on [CRAN](https://cran.r-project.org/web/packages/libstable4u/index.html), published 2023-09-01.

**Comment by ghost** [comment]
Sean thank you very much really appreciate. P.S. I tried installing libstable4u and it didnt work. Let me know if it works for you. Nico

**Comment by ghost** [comment]
Fixed it. Ended using: https://github.com/cran/libstable4u
Thanks again. nico

**Comment by shill1729** [comment]
Thanks for noticing this. I've updated it the dependencies here, sorry for the late reply.
